supervisely/supervisely

setup.py
=> Downgrade python-json-logger version in pip setup to restore compatibility with simplejson.

supervisely/api/file_api.py
The "upload" api request is handled by the remote server, that is a Unix, i suppose. So we can use a hardcoded "/" separator and don't care about the local OS.
=> fix upload_bulk (os.path.sep) -> "/"

supervisely/app/widgets/radio_group/template.html
**RadioGroup.get_value()** returns _label_ if it was specified (not value).
Changed template.html to fix it:
```:label="item.value"```
=> RadioGroup.get_value() fix

supervisely/app/fastapi/subapp.py
Right now enable_hot_reload_on_debug() function uses:
`hot_reload = arel.HotReload(paths=[arel.Path(".")])`
which in some cases leads to the infinite reload loop like this:
```
Detected file added at '.venv/bin/python', '.venv/bin/python3.10', '.venv/bin/python3'. Triggering reload...
Detected file added at '.venv/bin/python', '.venv/bin/python3.10', '.venv/bin/python3'. Triggering reload...
Detected file added at '.venv/bin/python', '.venv/bin/python3.10', '.venv/bin/python3'. Triggering reload...
```
I think we should add a list of excluded directories, which won't be scanned for changes.
Now it has the following just for example:
`exclude = [".venv", ".git", "tmp"]`
=> Added list of excluded directories in enable_hot_reload_on_debug()

supervisely/app/widgets/destination_project/destination_project.py, supervisely/app/widgets/destination_project/template.html, supervisely/app/widgets/image_region_selector/image_region_selector.py, supervisely/app/widgets/image_region_selector/script.js, supervisely/app/widgets/image_region_selector/template.html
DestinationProject got a checkbox for saving the source project datasets structure. 
ImageRegionSelector got a new parameter `points_disabled` for disabling green/red points addition by clicking inside the bbox.
bbox_changed event was fixed.
=> Widget DestinationProject was updated and fix for ImageRegionSelector was added

supervisely/volume/volume.py
**основное изменение:**
```
def compose_ijk_2_world_mat(spacing, origin, directions): ->
def compose_ijk_2_world_mat(meta):
try:
spacing = meta["spacing"]
origin = meta["origin"]
directions = meta["directions"]
except KeyError as e:
raise IOError(
f"Need the meta '{e}'' field to determine the mapping from voxels to world coordinates."
)
mat = np.eye(4)
mat[:3, :3] = (np.array(directions).reshape(3, 3) * spacing).T
mat[:3, 3] = origin
return mat
```
=> simplify compose_ijk_2_world_mat method in volume.py

.github/workflows/close_inactive_issues.yml
The action will run every hour at minute 30 and mark all issues as stale which has been inactive for 365 days. If the issue is being marked as stale has no activity for 7 days it will be closed.
=> Added action to close inactive issues

supervisely/app/widgets/transfer/transfer.py
Changed None value to [] for widget items, because the widget may disappear if the items data was None.
=> Bugfix in Transfer widget

supervisely/api/video/video_api.py
this block receives metas for unique hashes and create full list of metas for all hashes (incl. duplicates) in original list
=> fix video api upload_paths() for duplicate hashes

supervisely/project/project.py, supervisely/project/video_project.py
1. `sly.download_video_project()` and `sly.upload_video_project()` have an optional `include_custom_data` parameter set to False by default for reverse compatibility.
2. read_single_project() fix for different Project types.
=> Custom video data transfer

supervisely/app/fastapi/dialog_window.html
sly.app.show_dialog() will render HTML tags in the widget.
=> HTML tags fix in ShowDialog

supervisely/api/volume/volume_annotation_api.py, supervisely/geometry/mask_3d.py, supervisely/project/volume_project.py
1. **mask_3d**
https://github.com/supervisely/issues/issues/2920
```
File "/usr/local/lib/python3.8/dist-packages/supervisely/geometry/mask_3d.py", line 474, in base64_2_data
data = np.frombuffer(data_bytes, dtype=np.uint8).reshape(shape)
ValueError: cannot reshape array of size 168296448 into shape (512,512,321)
```
The np.frombuffer doesn't check the dtype, which defaults to `uint8`, but when downloading the geometry it comes in as `int16`.
2. **volume_annotation_api**
VolumeAnnotationAPI.upload_paths()
remove (comment) line where creating empty figures, they are already created on this step
3. volume_project
add type annotation to make it easier to work with the code
=> fix Mask3D array reshape + VolumeAnnotationAPI.upload_paths()

supervisely/app/widgets/sly_tqdm/sly_tqdm.py
Converts bytes to MB, GB, etc. if the "B" (bytes) was passed as unit and unit_scale is set to True for convenient display in Workspace Tasks's output.
Usage example:
```python
progress = sly.app.widgets.Progress()
with progress(
message="Downloading model...",
total=int(source.headers.get("Content-Length")),
unit="B",
unit_scale=True,
) as pbar:
```
Result output:
=> Bytes conversion in Progress widget

supervisely/io/fs.py
Added dirs_with_markers() - generator function that yields paths to directories that contain files with specific names (markers).
The markers can be specified as a single string or a list of strings.
If the check_function is specified, the markered directory will be yielded only if the check_function returns True.
If ignore_case is True, then the case of the marker names will be ignored.
```python
import supervisely as sly
input_path = '/home/admin/work/projects/examples'
markers = ['config.json', 'config.yaml']
def check_function(dir_path):
test_file_path = os.path.join(dir_path, 'test.txt')
return os.path.exists(test_file_path)
for directory in sly.fs.dirs_with_marker(input_path, markers, check_function, ignore_case=True):
print(directory)
```
=> Finding and checking directories with specific filename (marker)

supervisely/app/widgets/classes_table/classes_table.py, supervisely/app/widgets/classes_table/template.html
replaced the icon with SVG used in labeling tool.
before:
after:
=> Widget ClassesTable - change icon for polygon shapes and fix disable attribute

supervisely/project/project.py
`sly.Project.download()` will support the optional argument `save_image_meta`, which defaults to False for compatibility.
Example:
```python
sly.Project.download(api, PROJECT_ID, project_path, save_image_meta=True)
```
Will save corresponding image metas in the `meta` directory (e.g. `/download_path/project_name/dataset_name/meta`)
`sly.Project.upload()` will automatically detect if a meta folder exists and will try to read JSON file contents.
=> Support images meta for sly.Project.download() and upload()

supervisely/io/json.py
- If path is a directory, not a file
- If file from path does not exists
- For JSON decode errors: file path, line, column and position numbers, error message and document.
Error example:
```sh
RuntimeError: Can not decode json file with path /Users/iwatkot/Downloads/10903_test 3/ds0/annotation.json: Invalid control character at at line number: 1, column: 3, position: 2. Document: "{
"description": "",
"key": "233ed5ab8d7d4349bad8a5a30513519d",
"tags": [],
"objects": [],
"framesCount": 20,
"frames": []
}
```
=> Detailed error messages for load_json_file()

supervisely/volume/volume.py
`sly.volume.has_valid_ext` returns  `is_valid_ext(get_extension(path))`:
1. `get_extension` -> `str` or **`None`**
2. `is_valid_ext` utilizes the `str.lower()` method (fails if `None` is provided).
added argument type checking
=> Handle non-string input in sly.volume.is_valid_ext(ext: str)

setup.py, supervisely/video/video.py
- Change deprecated `skvideo` to `cv2` in `sly.video.get_image_size_and_frames_count(path)` to get frames count and frame size 
- Fix reading video meta using `ffprobe` (add `pts_time` property)
- Check timecodes are not `None`
=> Fix deprecated skvideo in sly.video.get_image_size_and_frames_count(path)

supervisely/api/dataset_api.py, supervisely/api/module_api.py, supervisely/api/project_api.py
Changes: 
- project_api 
- add team_id in ProjectInfo
- add def remove_permanently
- add def get_list_all
- update get_archivation_list to work via get_list_all for backwards compatibility
- dataset_api
- add team_id and workspace_id in DatasetInfo
- update type for arg 'page' in def get_list_all and its docstring
- update return for def get_list_all to return entities as DatasetInfo
- module_api
- add ApiField - PRESERVE_PROJECT_CARD
=> Add/update Projects and Datasets methods: remove_permanently, get_list_all

supervisely/api/file_api.py, supervisely/task/progress.py
1. Bug fix in progress (tqdm) - `TypeError: need_report() missing 1 required positional argument: 'self'`
2. FileApi - added progress logging in the `api.file.download_input(save_path)` method:
```python
api.file.download_input(save_path, log_progress=True)
```
=> Bug fix in progress. FileApi - added log_progress argument to api.file.download_input

supervisely/api/file_api.py
in `api.file.get_directory_size`:
- check if directory is on local agent, then optimized method will be used (without api requests)
- replaced `self.list2` > `self.list`
in `api.file.download_directory` method:
- call `progress_cb` when downloading a directory from local agent
=> FileApi - optimized getting directory size on agent

supervisely/app/fastapi/templating.py, supervisely/io/exception_handlers.py
1. Upgraded `js_bundle_version = 2.1.73` (fixed `<sly-editor>` and `<sly-file-storage-upload>` widgets)
2. Added `has_ui` argument in the `handle_exceptions` decorator to preserve exception type (instead of `DialogWindowError`) in the apps that do not have UI
now it can be used in the following ways:
a. with argument
```python
@sly.handle_exceptions(has_ui=False)
def my_func():
```
b. without argument
```python
@sly.handle_exceptions # equal to @sly.handle_exceptions(has_ui=True)
def my_func():
```
=> Improve exception handler decorator. Upgrade js_bundle_version to 2.1.73

supervisely/api/pointcloud/pointcloud_episode_annotation_api.py
Fixed incorrect uploading of figures (starting from the first frame of episodes even if they were supposed to be, for example, on frames 5 and 6).
After the fix, they will be uploaded to the correct frames (in this case – on 5 and 6 frames instead of 1 and 2 frames).
=> PointcloudEpisodeAnnotationAPI - fixed indexes of frames in api.pointcloud_episode.annotation.append

supervisely/api/dataset_api.py, supervisely/api/project_api.py, tests/test_api_dataset_remove_permanently.py, tests/test_api_project_archive.py, tests/test_api_project_remove_permanently.py
- update methods to delete in batches with max allowed size of 50 (by default)
- add unit tests for:
- `api.project.remove_permanently`
- `api.dataset.remove_permanently`
- `api.project.archive`
=> api.project.remove_permanently and api.dataset.remove_permanently add batch and progress_cb args

setup.py
Following dependencies updated:
- "Shapely>=1.7.1, <=2.0.2"
- "pydantic>=1.7.4, <=2.5.0"
- "pandas>=1.1.3, <=2.1.4"
- "urllib3>=1.26.15, <=2.1.0"
- "jsonschema>=2.6.0,<=4.20.0"
=> Updated dependencies versions: Shapely, pydantic, pandas, urllib3, jsonschema

supervisely/app/widgets/fast_table/fast_table.py, supervisely/app/widgets/fast_table/script.js
- unnecessary try-except (exception will be handled in sly.Application)
- fix: KeyError (on the first attempt to search before sorting) id data loaded by `read_json()`
- update: check if cell is empty to show the postfix
=> fix FastTable widget: fix bug, update postfix displaying, remove redundant log

supervisely/api/video/video_api.py
Reason: [SDK: frames_to_timecodes is None if RAW_VIDEO_META is True](https://github.com/supervisely/issues/issues/4154)
=> Removed raw video data parameter for API request

supervisely/api/labeling_job_api.py
api.labeling_job.create() method now supports two optional bool arguments:
- dynamic_classes: Allows to use dynamic classes in labeling job
- dynamic_tags: Allows to use dynamic tags in labeling job
```python
new_label_jobs = api.labeling_job.create(
user_name,
dataset_id,
user_ids=[340],
readme="Readme text",
description="Work for labelers",
objects_limit_per_image=5,
tags_limit_per_image=3,
dynamic_classes=True,
dynamic_tags=True,
)
```
=> DynamicClasses and DynamicTags features for LabelingJobs API

supervisely/nn/inference/tracking/tracker_interface.py
disable saving frames in hot_cache (RAM) in TrackerInterface
- if smart caching is used (`frame_loader=self.download_frame`)
- if `load_all_frames is False`
=> Update RAM usage in tracking interface

supervisely/app/widgets/image_region_selector/script.js
Point sizes in the ImageRegionSelector widget have wrong calculations after changing images in the widget.
This fix will solve the issue.
=> ImageRegionSelect point size fix

supervisely/app/widgets/select_dataset/select_dataset.py
Changing/selecting a project if the "all datasets" checkbox is selected will not trigger the `value_changed` callback
=> Widget SelectDataset: fix bug in value_changed cb

supervisely/io/fs.py, supervisely/project/project.py
- new argument in `sly.fs.subdirs_tree` to ignore subdirs of the specified dirs
- fix: using `dataset_class` instead of `Dataset` (videos, volumes, pointclouds, episodes projects)
- fix: get the correct `project_dir` and dataset names in dataset class initialization
=> Fix bugs when reading a local project / dataset. New arg in sly.fs. subdirs_tree

supervisely/app/fastapi/templating.py, supervisely/app/widgets/file_storage_upload/file_storage_upload.py, supervisely/convert/base_converter.py, supervisely/convert/pointcloud_episodes/pointcloud_episodes_converter.py, supervisely/convert/pointcloud_episodes/sly/sly_pointcloud_episodes_converter.py
* Add warning if frames mapping file not found for PCDe import.
* Add support for uploading PCDe without rimgs.
* Set log level to info for data without annotation format.
* Upgrade JS bundle to "2.1.79".
* Fix get_path method in FileStorageUpload widget
=> Upgrade JS bundle to 2.1.79. Fixes for import PCDe and FileStorageUpload widget

supervisely/__init__.py, supervisely/api/module_api.py, supervisely/api/task_api.py
Tasks can be limited to be visible only in the specified workspace.
```python
import supervisely as sly
api = sly.Api.from_env()
agent_id = 469
module_id = 54
task_info = api.task.start(
agent_id=agent_id,
module_id=module_id,
workspace_id=workspace_id,
limit_by_workspace=True,
)
```
=> Limit task by workspace

supervisely/_utils.py, supervisely/api/image_api.py
Works for:
- preview_url property of ImageInfo objects
- api.image.preview_url() method
=> Shifting to ImageProxy for resizing and compressing images

supervisely/api/image_api.py, supervisely/convert/base_converter.py, supervisely/convert/converter.py, supervisely/convert/image/csv/csv_converter.py, supervisely/convert/image/image_converter.py, supervisely/convert/image/medical2d/medical2d_converter.py, supervisely/convert/image/medical2d/medical2d_helper.py, supervisely/convert/image/multi_view/multi_view.py, supervisely/convert/image/multispectral/multispectral_converter.py, supervisely/convert/image/sly/sly_image_converter.py, supervisely/convert/image/sly/sly_image_helper.py, supervisely/convert/video/sly/sly_video_helper.py, supervisely/convert/volume/dicom/dicom_converter.py
- new method `api.image.upload_medical_images()` to upload 2D DICOM images in groups
- Add grouping functionality for 2D DICOM images
- Preserve metadata for 3D DICOM volumes
- Implement GraphNode shape in SLY video converter
- Address corner cases in SLY image converter
- used sly.ApiContext to improve annotations uploading performance
=> New Import: Group 2D DICOM, meta from 3D DICOM. Graph shape for videos. Handling corner cases. New method api.image.upload_medical_images()

supervisely/pointcloud_annotation/pointcloud_episode_annotation.py
When removing some frames from an episode, `frame_index` can be greater than `frames_count` (will raise the `ValueError No frame with index XX in annotation` exception )
```python
ann: sly.PointcloudEpisodeAnnotation 
ann.get_figures_on_frame(frame_index)  # ValueError
ann.get_tags_on_frame(frame_index)  # ValueError
ann.get_objects_on_frame(frame_index) #  ValueError
```
=> Fix PointcloudEpisodeAnnotation: return empty collection if frame not found in annotations

supervisely/api/file_api.py, supervisely/app/fastapi/offline.py
When reloading dynamic widget fast, there was an error uploading offline session files.
This PR fixes it by uploading offline session files consequently
=> Offline session dump fix

supervisely/decorators/inference.py, supervisely/nn/inference/inference.py
Improved inference performance and code usability.
nn.Inference:
- changed arguments of `predict_batch` and `predict_batch_raw`. Now they only support np.arrays in RGB format (actually, we somewhere passed RGB images to predict_batch: [[1]](https://github.com/supervisely/supervisely/blob/e112304be3974b974fdec9383fbf0b1fbc310ed0/supervisely/nn/inference/inference.py#L947), [[2]](https://github.com/supervisely/supervisely/blob/e112304be3974b974fdec9383fbf0b1fbc310ed0/supervisely/nn/inference/inference.py#L1229)).
- optimized most inference methods (removed redundant writing of images in tmp dir)
- added fallback logic in `_inference_auto`
- added batched inference for sliding_window
- removed _inference_images_batch
- removed _inference_images_dir
- fixed …
=> Inference optimizations & fallback logic

supervisely/convert/base_converter.py, supervisely/convert/image/image_converter.py, supervisely/convert/image/sly/sly_image_converter.py, supervisely/project/project_settings.py, supervisely/video_annotation/video_figure.py
- Added a new labeling interface `fisheye` in the project settings
- For importing without annotation, AutoImport will search for image meta files (in any folder with the name `meta`). It will be used for the new labeling interface (`fisheye`).
- fix smart_tool_input attribute passing
=> Fisheye - the new labeling interface. AutoImport search metadata for images.

supervisely/api/dataset_api.py
Usage example:
```python
import supervisely as sly
api = sly.Api.from_env()
project_id = 123
dataset_id = 456
datasets = api.dataset.get_nested(project_id, dataset_id)
for dataset in datasets:
print(dataset.name, dataset.id) # Output: ds1 123
```
=> Get list of nested datasets in the given dataset

supervisely/convert/base_converter.py, supervisely/convert/image/multi_view/multi_view.py, supervisely/convert/image/sly/sly_image_converter.py
1. Improvement: Allow the import of Supervisely format annotations into an existing project with the multi-view settings already enabled:
- Added "multiview" to labeling interface validation in the sly converter
- Updated multi-view converter validation to return `False` if any possible annotation files are found (to avoid converter conflicts)
2. Fix: Update all project settings when updating the labeling interface
=> AutoImport: Import Supervisely annotations into project with multi-view labeling interface

supervisely/__init__.py, supervisely/api/app_api.py
-  `WorkflowSettings` as interface which helps to create settings to customize the appearance and behavior of the workflow node
-  `WorkflowMeta` as interface where you assign settings to main or relation node. It's easy to convert the `meta` in the dictionary via `as_dict` property or get it right after initialization with the `create_as_dict()` class method
- The `_workflow_compatibility_version_cache` global variable stores the validation results for the current session for each new `min_instance_version` that has already been validated, to avoid unnecessary API calls.
- The `check_instance_compatibility` decorator is used on each `Workflow` method to check compatibility. If new methods will require a new instance version - it is necessary to add this to the decorator as argument.
- …
=> Add instance compatibility check for Workflow methods. Add dataclasses WorkflowSettings, WorkflowMeta.

supervisely/nn/benchmark/evaluation/instance_segmentation_evaluator.py, supervisely/nn/benchmark/evaluation/object_detection_evaluator.py, supervisely/nn/benchmark/utils.py, supervisely/nn/benchmark/visualization/vis_metric_base.py, supervisely/nn/benchmark/visualization/vis_metrics/frequently_confused.py, supervisely/nn/benchmark/visualization/vis_texts.py
- fix typo `predctions` → `predictions`
- raise error if no predictions
- show notification instead of chart in `Frequently Confused Classes` (if not found any confused pairs)
=> Model benchmark. Stage 2.1. Fixes and corner case handling

supervisely/nn/benchmark/base_benchmark.py, supervisely/nn/benchmark/coco_utils/sly2coco.py, supervisely/nn/benchmark/evaluation/base_evaluator.py, supervisely/nn/benchmark/evaluation/coco/metric_provider.py, supervisely/nn/benchmark/evaluation/instance_segmentation_evaluator.py, supervisely/nn/benchmark/evaluation/object_detection_evaluator.py, supervisely/nn/benchmark/utils.py, supervisely/nn/benchmark/visualization/vis_metric_base.py, supervisely/nn/benchmark/visualization/vis_metrics/explorer_grid.py, supervisely/nn/benchmark/visualization/vis_metrics/frequently_confused.py, supervisely/nn/benchmark/visualization/vis_metrics/overview.py, supervisely/nn/benchmark/visualization/vis_texts.py, supervisely/nn/benchmark/visualization/visualizer.py, supervisely/nn/inference/session.py
- using selected classes from the training or the evaluator app
- allow "classes" key in inference_settings
From PR https://github.com/supervisely/supervisely/pull/1095:
- fix typo `predctions` → `predictions`
- raise error if no predictions
- show notification instead of chart in `Frequently Confused Classes` (if not found any confused pairs)
=> Model benchmark stage 2.2. Selected classes

supervisely/convert/converter.py
set `include_folders=False` (list only files from remote storage)
=> fix AutoImport: list only files from remote storage (exclude folders)

supervisely/nn/inference/cache.py
When an error happens in PersistentImageTTLCache clean the cache
=> Handle cache error

supervisely/project/download.py, supervisely/project/project.py, supervisely/project/video_project.py
Fix overhead for projects with huge amount of datasets
=> Add skip_create_readme parameter to download functions to control README generation

supervisely/app/widgets/transfer/style.css, supervisely/app/widgets/transfer/template.html, supervisely/app/widgets/transfer/transfer.py
The feature allows to set the widget's width in pixels.
Example:
```python
transfer = Tranfser(items, width=300)
```
=> Width for the Transfer widget

supervisely/api/entity_annotation/figure_api.py
This PR refactors the async listing method for figures in FigureApi to improve performance through batching. The refactoring introduces a new `batch_size` parameter and restructures the code to process image IDs in configurable batches rather than sending all IDs in a single request.
- Adds configurable `batch_size` parameter (default 300) for controlling request batch sizes
- Restructures async figure downloading to use batch processing strategy
- Implements parallel processing of batches with small delays to reduce server load
=> Refactor async listing method for figures in FigureApi
