supervisely/supervisely

.gitignore, setup.py
It will be convenient to:
1. Either install supervisely from pip
2. Or simply clone and run `pip install -e .`
The PR is opened to all kinds of comments.
=> Pip package added

agent/README.md
Updated the links to lead to the current docs page address
=> Docs link fix

supervisely_lib/__init__.py, supervisely_lib/api/project_api.py, supervisely_lib/api/video/video_api.py, supervisely_lib/api/video/video_tag_api.py, supervisely_lib/app/app_service.py, supervisely_lib/decorators/profile.py
- added AppService.periodic functional
- added update_fields decorator
- added API method video.add_tag
- added API method api.video_api.url method
=> updates for APP Engine && SDK

supervisely_lib/annotation/annotation.py, supervisely_lib/project/project.py
* allows to convert sly.Project to instance segmentation task
* allows to convert sly.Annotation to instance segmentation task
=> instance segmentation task methods added

supervisely_lib/aug/imgaug_utils.py, supervisely_lib/project/project.py
* target classes bug fixed
* all segmentation methods in one function now
* img_aug segmentation methods updated for segmentation task
=> segmentation methods merged to one function

supervisely/__init__.py, supervisely/api/pointcloud/pointcloud_episode_annotation_api.py, supervisely/pointcloud/pointcloud.py, supervisely/project/pointcloud_episode_project.py, supervisely/project/project.py
* upload method optimizations
* project reader log on exeption
* handling missfile / missannotation cases
=> Pointcloud Episode methods updates

MANIFEST.in, setup.py, supervisely/api/api.py, supervisely/api/github_api.py, supervisely/api/user_api.py, supervisely/app/__init__.py, supervisely/app/content.py, supervisely/app/fastapi/__init__.py, supervisely/app/fastapi/subapp.py, supervisely/app/fastapi/templating.py, supervisely/app/jinja2.py, supervisely/app/singleton.py, supervisely/app/widgets/__init__.py, supervisely/app/widgets/notification_box/notification_box.css, supervisely/app/widgets/notification_box/notification_box.html, supervisely/app/widgets/notification_box/notification_box.py, supervisely/app/widgets/radio_table/radio_table.css, supervisely/app/widgets/radio_table/radio_table.html, supervisely/app/widgets/radio_table/radio_table.py
- add radio table widget
- add notification box (warning)
- remove LastStateJson
=> app engine 2: first widgets and reimplemented app content

supervisely/__init__.py, supervisely/decorators/inference.py
process_image_with_crop -> process_image_roi
state["rectangle-crop"] -> state["rectangle"]
=> updated inference decorator name and rectangle name in state

supervisely/video/get_video_info.sh, supervisely/video/video.py
=> supervisely.video.video.get_info method fix

supervisely/api/file_api.py, supervisely/api/project_api.py
add new method api.project.images_grouping(id, enable, tag_name)
=> add new method api.project.images_grouping(id, enable, tag_name)

supervisely/aug/imgaug_utils.py
New features:
- Support new types of imgaug augmentations with {"x": (), "y": ()} parameters (for example, Affine)
- Support augmentations for bounding boxes
- Support augmentations for instance segmentation
- Support augmentations for instance and semantic segmentation simultaneously
=> Expand augmentations

supervisely/app/fastapi/__init__.py, supervisely/app/fastapi/utils.py, supervisely/app/widgets/sly_tqdm/sly_tqdm.py
* run_sync method added
* SlyTqdm widget updated
=> Added method to run Async in Sync functions

setup.py
https://github.com/supervisely/issues/issues/837
=> import supervisely hotfix

supervisely/api/pointcloud/pointcloud_episode_api.py
- get frame name map method polyfield added
=> [hotfix] Download PCL Project frames mapping 

supervisely/geometry/polyline.py
bug fix crop lines with shapely.geometry
=> bug fix crop lines

docs/source/_static/css/custom.css, supervisely/annotation/annotation.py, supervisely/annotation/label.py, supervisely/api/image_api.py, supervisely/project/project_meta.py
add new examples for ObjClassCollection, TagCollection, TagMetaCollection, ProjectMeta
add remove, remove_batch methods to SDK api.image
fix class badge colors in SDK docs
=> SDK update

docs/source/_static/css/custom.css, supervisely/api/annotation_api.py, supervisely/api/app_api.py, supervisely/api/dataset_api.py, supervisely/api/file_api.py, supervisely/api/image_api.py, supervisely/api/labeling_job_api.py, supervisely/api/pointcloud/pointcloud_api.py, supervisely/api/project_api.py, supervisely/api/role_api.py, supervisely/api/team_api.py, supervisely/api/user_api.py, supervisely/api/video/video_api.py, supervisely/api/volume/volume_api.py, supervisely/api/workspace_api.py
add PointcloudInfo, VideoInfo, VolumeInfo, RoleInfo, AppInfo, LabelingJobInfo, ImageInfo, ProjectInfo, DatasetInfo, TeamInfo, AnnotationInfo, WorkspaceInfo, UserInfo, FileApi to supervisely.api
custom.css change class badge color in docs
=> Supervisely.api SDK update

supervisely/geometry/bitmap.py, supervisely/geometry/bitmap_base.py
bitmap_base - only formatting!
=> bitmap validation ([0, 1][0, 255],[False, True]

supervisely/annotation/annotation.py, supervisely/annotation/label.py
- fill_rectangle param in draw_pretty()
- get_thickness() in draw_pretty()
- get_font() in label
=> fill_rectangles param added to ann.draw_pretty()

supervisely/api/image_api.py
Added batch_size argument to add_tag_batch method of ImageApi
=> Added batch_size argument to add_tag_batch method of ImageApi

supervisely/app/widgets/project_thumbnail/project_thumbnail.py, supervisely/app/widgets/table/table.py
Added set method to project thumbnail widget
Added method to update multiple cells of the table widget
=> Project thumbnail and table widgets enhancement

supervisely/app/v1/app_service.py
Exit signals handlers for windows
=> Exit signals for windows

supervisely/api/video/video_api.py
**VideoApi**
`raise NotImplementedError` for 3 download methods:
- `download_save_range`
- `download_range_by_path`
- `download_range_by_id`
=> videoApi download frame range methods are unavailable

supervisely/app/widgets/select/select.py
chech len(self._groups[0]) error
=> bug-fix-select-widget

cli/supervisely-app.sh
archive with .gitignore fix
slug parsing from git config removed
=> supervisely-app cli release confirmation

supervisely/app/widgets/grid_gallery/grid_gallery.py, supervisely/app/widgets/labeled_image/labeled_image.py
Added zoom to figure parameters to labeled image and grid gallery widgets
=> Add zoom to figure

supervisely/app/import_template.py
bug fix no file and folder error
=> Import template no path

supervisely/app/import_template.py
=> bug_fix_production_path

supervisely/app/widgets/input_tag/input_tag.py
Now you can pass None to set method
=> Widget InputTag update

supervisely/nn/inference/video_inference.py, tests/test_video_rotations.py
- vidcap.set(cv2.CAP_PROP_ORIENTATION_AUTO, 0)
- old code is commented out
=> fix reading frames from video (frame rotation) - opencv issue

supervisely/nn/inference/video_inference.py, tests/test_video_rotations.py
change CAP_PROP_ORIENTATION_AUTO flag from 0 to 1
=> fix reading frames from video (change video orientation flag value) - opencv issue

supervisely/app/fastapi/templating.py
sessionTagsCombination option added in sly-select-app-session widget
=> js_bundle_version 2.1.34

supervisely/app/fastapi/offline.py
Remove `.py`, `.pyc`, `.md`, `.sh` files
=> Apps offline session files (filter before uploading to Team files)

supervisely/geometry/graph.py, supervisely/nn/inference/inference.py, supervisely/nn/inference/pose_estimation/pose_estimation.py
transfered point_names, keypoint_template and model_meta initialization to sly.nn.inference.PoseEtimation
=> sly.nn.inference.pose_estimation refactoring + added NotImplementedError for disabled=True in sly.Node

supervisely/app/fastapi/offline.py, supervisely/app/widgets/input_tag/input_tag.py, supervisely/app/widgets/input_tag/template.html
- max width to InputTag template
- remove `missing_ok=True` in offline sessions files filter
=> Widget InputTag (added max width for widget) + fix apps shutdown function

supervisely/app/widgets/input/input.py, supervisely/app/widgets/input/template.html
It's possible to create hidden input fields with type="password".
=> New "type" attribute for Input()

supervisely/app/widgets/__init__.py, supervisely/app/widgets/grid_gallery/grid_gallery.py, supervisely/app/widgets/image_region_selector/image_region_selector.py, supervisely/app/widgets/image_region_selector/script.js, supervisely/app/widgets/image_region_selector/styles.css, supervisely/app/widgets/image_region_selector/template.html, supervisely/app/widgets/radio_table/radio_table.py
New widget - ImageRegionSelector
New parameter `show_preview` for GridGallery.
Fix for subtitles in RadioTable widget.
=> ImageRegionSelector widget was added. GridGallery got new optional parameter `show_preview`. RadioTable subtitles fix.

cli/supervisely-app.sh
do not archive files added to .gitignore but already committed
=> apps cli. exclude committed files from archive

supervisely/api/module_api.py, supervisely/api/project_api.py
add archive_projects and archive_project methods to ProjectApi
add API fields to ModuleApi
=> archive + archive_batch

supervisely/annotation/annotation.py
to use in updated [import-images-from-csv](https://github.com/supervisely-ecosystem/import-images-from-csv)
=> add img_size type Tuple[None, None]

supervisely/app/widgets/select/select.py, supervisely/app/widgets/select/template.html, supervisely/app/widgets/widget.py
+ позволяет дизейблить отдельные опции или группы селектора
+ фикс метода __init__ класса Widget
+ делает колбэк на изменение выбора асинхронным
=> Widget select enhancement

supervisely/cli/teamfiles/teamfiles_upload.py, supervisely/task/progress.py
https://github.com/supervisely/issues/issues/2191
=> add new progress in cli

supervisely/api/file_api.py, supervisely/cli/teamfiles/teamfiles_upload.py
https://github.com/supervisely/issues/issues/2227
=> path separator fix

supervisely/api/pointcloud/pointcloud_episode_api.py, supervisely/api/pointcloud/pointcloud_object_api.py, supervisely/api/pointcloud/pointcloud_tag_api.py
Add to SDK for PCD and PCE:
for point cloud (not supported in API for episodes)
- api.pointcloud.tag.add()
- api.pointcloud.tag.remove()
- api.pointcloud.tag.update()
for point cloud object
- api.pointcloud.object.tag.add()
- api.pointcloud.object.tag.remove()
- api.pointcloud.object.tag.update()
=> add api.pointcloud.tag.add / api.pointcloud.object.tag.add method for PCD and PCE

tests/add_upd_remove_tag_to_pcd.py, tests/add_upd_remove_tag_to_pcd_ep_object_with_frames.py, tests/add_upd_remove_tag_to_pcd_object.py
For PCD
-  api.pointcloud.tag.add()
-  api.pointcloud.tag.remove()
-  api.pointcloud.tag.update()
-  api.pointcloud.object.tag.add()
-  api.pointcloud.object.tag.remove()
-  api.pointcloud.object.tag.update()
For PCE
-  api.pointcloud_episode.object.tag.add()
-  api.pointcloud_episode.object.tag.remove()
-  api.pointcloud_episode.object.tag.update()
=> add-update-remove-pcd-tag-pcd-pce-object-tag

supervisely/app/fastapi/subapp.py, supervisely/app/fastapi/templating.py
https://github.com/supervisely/issues/issues/2296
=> Added Application stop method

supervisely/project/pointcloud_episode_project.py
=> fix download pcd episode without pcd error

supervisely/app/widgets/__init__.py, supervisely/app/widgets/transfer/template.html, supervisely/app/widgets/transfer/transfer.py
ui-widget-demos PR: https://github.com/supervisely-ecosystem/ui-widgets-demos/pull/103
=> Added Transfer widget

supervisely/app/widgets/select/select.py
=> Widget Select bug fix

supervisely/nn/inference/tracking/functional.py, supervisely/nn/inference/tracking/point_tracking.py, supervisely/nn/inference/tracking/tracker_interface.py
Add flag to TrackerInterface: if `load_all_frames` is True, all frames will be loaded before tracking starts, otherwise tracking will download, predict and update frame by frame
=> Tracking inference notifications

supervisely/app/fastapi/subapp.py, supervisely/app/import_template.py, supervisely/app/widgets/button/button.py, supervisely/app/widgets/card/card.py, supervisely/app/widgets/file_storage_upload/file_storage_upload.py, supervisely/app/widgets/file_storage_upload/template.html, supervisely/app/widgets/select_dataset/select_dataset.py, supervisely/app/widgets/tabs/tabs.py, supervisely/app/widgets/tabs/template.html, supervisely/app/widgets/team_files_selector/team_files_selector.py
import app template dev and adv debug modes
add functionality to/fix widgets:
Button - add `icon`, `button_type`,  `plain` properties
Card - add `is_locked()` method
FileStorageUpload - add `team_id` to template.html
SelectDatasets - add allowed project types parameter
Tabs - add tab clicked callback
TeamFilesSelector - add `get_selected_items()` method to get item type
=> Import app template and minor widgets improvements

supervisely/app/fastapi/templating.py
=> js_bundle_version 2.1.48

supervisely/api/volume/volume_annotation_api.py, supervisely/api/volume/volume_api.py, supervisely/api/volume/volume_figure_api.py, supervisely/task/progress.py
+ mask3d geometry upload function `upload_sf_geometry()`
+ update `volume_annotation.append()` with `spatial_figures`
+ tqdm fix for production: now `is_size == True` for default `unit` values
+ update docstring in `volume_figure_api._append_bulk_mask3d()`
+ change logger info to debug for `volumes.upload_np()`
=> mask3d geometry upload function + some updates and fix

supervisely/project/project.py
Generator function that yields the item name, image path, and annotation path for each item in a dataset.
=> Added items() for Project.Dataset

supervisely/app/widgets/grid_plot/grid_plot.py, supervisely/app/widgets/line_plot/line_plot.py
Add more comments to clarify several functions signature
=> Widget lineplot fix

supervisely/app/fastapi/subapp.py
Issue: https://github.com/supervisely/issues/issues/2841
=> Fixed compatibility with old 2.0 applications

supervisely/app/widgets/sly_tqdm/sly_tqdm.py, supervisely/app/widgets/sly_tqdm/template.html
1. Fixed Bug when hide_on_finish argument does nothing
2. Added set_message method
=> Widget ProgressBar update

supervisely/io/fs.py
- Added function string_to_byte_size(), which returns byte size representation from a string representation. E.g. "1.5Kb" -> 1572864
- archive_directory()'s split parameter can now be int (in bytes) or str ("2.0Mb", "1.2Gb", etc.)
=> String repr of split size in archive_directory()

supervisely/api/module_api.py, supervisely/api/project_api.py
- api.project.get_archivation_list() that use API method `projects.list.all` to get list of projects which could be archived
- new ApiFields
=> add -> api.project.get_archivation_list()

.github/workflows/manual_sdk_nvidia_docker.yml, .github/workflows/manual_sdk_pip_docker.yml, .github/workflows/sdk_pip_docker.yml, base_images/py_sdk/Dockerfile, docker_images/README.md, docker_images/collaboration/Dockerfile, docker_images/data_operations/Dockerfile, docker_images/development/Dockerfile, docker_images/import_export/Dockerfile, docker_images/labeling/Dockerfile, docker_images/synthetic/Dockerfile, docker_images/system/Dockerfile, docker_images/visualization_stats/Dockerfile
Add docker images for app categories
Separate nvidia docker build github action
Update github action to build docker images for app categories on SDK release
=> add docker images for app categories

supervisely/project/project.py
- find_project_dirs() - generator function that yields all valid project dirs in a given directory (including sub dirs)
- read_single_project() uses find_project_dirs(). Raises errors if the number of valid project dirs != 1.
=> Find valid project dir in read_single_project()

supervisely/cli/release/release.py, supervisely/cli/release/run.py
1) Print App Key
2) -a absolute path
3) prohibit empty release description
4) при первом релизе приложения в CLI запрашивать шарить ли эпу на весь инстанс (в сообщении подробно прописать, что это приватное приложение будет доступно всем пользователям на вашем приватном инстансе)
=> Release CLI new features

supervisely/api/module_api.py, supervisely/api/project_api.py
update `archive()`, `archive_batch()` with link for annotation backup
add `check_imageset_backup()` to check link for files backup for images project
add  `ApiField.ANN_ARCHIVE_URL`
=> archive images project in two parts

supervisely/__init__.py, supervisely/app/fastapi/subapp.py, supervisely/app/v1/app_service.py, supervisely/function_wrapper.py, supervisely/io/exception_handlers.py
- search error handlers based on patterns (function + decorator) - included in sly.AppService and sly.Application
- user-friendly error logs (for developers)
- show modal DialogWindowError in apps with gui (2.0, 1.0)
- patterns (pattern-handler nested dictionary)
sly.handle_exceptions(exception) - decorator
```python
import supervisely as sly
@sly.handle_exceptions
def my_func():
```
sly.handle_exception(exception) - function
```python
import supervisely as sly
try:
except Exception as e:
exception_handler = sly.handle_exception(e)
if exception_handler:
exception_handler.raise_error()
else:
raise
```
=> Handle exceptions

supervisely/io/fs.py
Can be used for finding valid directories in a user's input data while working with Import applications regardless of file structure and allowing to processing of several series of data (e.g. projects) at once.
Can be implemented here: 
- https://ecosystem.supervisely.com/apps/import-coco
- https://ecosystem.supervisely.com/apps/import-coco-keypoints
- https://ecosystem.supervisely.com/apps/import-pascal-voc
- https://ecosystem.supervisely.com/apps/import-cityscapes
- ...
Usage example:
```python
INPUT_DATA = "/Users/iwatkot/Coding/Supervisely/filter-dirs/code/input_data"
def check_function(directory) -> bool:
images_dir = os.path.join(directory, "images")
annotations_dir = os.path.join(directory, "annotations")
return os.path.isdir(images_dir) and os.path.isdir(annotations_dir)
for …
```
=> Finding directories matching specific requirements

supervisely/app/widgets/sly_tqdm/sly_tqdm.py, supervisely/task/progress.py
* add getpartial() method to CustomTqdm
* add default unitdivisor=1024
=> add getpartial() method to CustomTqdm and add default unitdivisor=1024

supervisely/annotation/obj_class.py, supervisely/imaging/color.py
**obj_class.py**
- update  `def from_json` for `ObjClass` , if hex is incorrect  - `color = random_rgb()` 
----
**color.py**
- add `def _validate_hex_color` - to check HEX format
- update `def hex2rgb` with this validation and raise `ValueError` instead of assert
=> hex color validation

supervisely/project/project_meta.py
=> Human-readable error for incorrect meta.json

supervisely/api/volume/volume_annotation_api.py, supervisely/api/volume/volume_figure_api.py, supervisely/geometry/mask_3d.py, supervisely/io/fs.py, supervisely/project/volume_project.py, supervisely/video_annotation/key_id_map.py, supervisely/volume/nrrd_loader.py, supervisely/volume/stl_converter.py, supervisely/volume/volume.py, supervisely/volume_annotation/volume_figure.py
**volume_annotation_api.py**
- `def upload_paths`
- additionally as option receives List with mask directories in which stored NRRD files with geometries
- if directory "interpolations' exists, checks this dir and convert old STL to NRRD with `stl_converter.to_nrrd`, updates annotaition and project meta with new items if it needs with `_update_on_transfer `
- `def _update_on_transfer `  - creates new Class, Objec and Figure for converted STL, then removes old ones from annotation
- `def _prepare_convertation_paths`  - Check dir and create paths for NRRD files if STL files need to be converted.
----
**volume_figure_api.py** 
- `def download_sf_geometries` - new method that helps to download geometries to the specified paths
- `def load_sf_geometry` - this method is an updated copy of `def …
=> stl to nrrd

supervisely/app/widgets/image_annotation_preview/script.js, supervisely/app/widgets/labeled_image/labeled_image.py, supervisely/app/widgets/timeline/timeline.py
- fix ImageAnnotationPreview widget size
- change empty message parameter for LabeledImage
- fix annotation in timeline widget
=> fix ImageAnnotationPreview widget size

supervisely/annotation/annotation.py, supervisely/annotation/label.py, supervisely/app/fastapi/subapp.py, supervisely/app/v1/app_service.py, supervisely/io/exception_handlers.py
- better error logs for v2 apps
- better error logs for v1 apps (AppService)
- better exception for `sly.Application.from_json` and `sly.Label.from_json`
- small updates in `dev_logging` in `handle_exception` and show it only if `is_development`
- new patterns for `handle_exception`
=> Renders preview fix app logs

supervisely/app/widgets/__init__.py, supervisely/app/widgets/pagination/pagination.py, supervisely/app/widgets/pagination/template.html
=> add widget Pagination

supervisely/app/widgets/__init__.py, supervisely/app/widgets/cascader/cascader.py, supervisely/app/widgets/cascader/template.html
=> add widget Cascader

supervisely/app/widgets/__init__.py, supervisely/app/widgets/time_picker/template.html, supervisely/app/widgets/time_picker/time_picker.py
=> add widget TimePicker

supervisely/app/fastapi/templating.py, supervisely/app/widgets/nodes_flow/nodes_flow.py, supervisely/app/widgets/sidebar/sidebar.py, supervisely/app/widgets/sidebar/template.html
NodesFlow - improved UI, added Node header icon
Sidebar - aditioinal options for sidebar layout
=> Widgets NodesFlow and Sidebar additional options and styles

supervisely/api/pointcloud/pointcloud_api.py
Added file extensions in examples
=> Minor changes in docstrings for pointcloud api

supervisely/app/widgets/__init__.py, supervisely/app/widgets/element_tag/element_tag.py, supervisely/app/widgets/element_tag/template.html
=> add ElementTag widget

supervisely/app/widgets/__init__.py, supervisely/app/widgets/element_tags_list/element_tags_list.py, supervisely/app/widgets/element_tags_list/template.html
есть проблема с анимацией закрытия тега, она чисто визуальная
=> add ElementTagsList widget

supervisely/__init__.py, supervisely/annotation/label.py, supervisely/api/annotation_api.py, supervisely/api/module_api.py, supervisely/app/fastapi/subapp.py, supervisely/app/widgets/switch/switch.py, supervisely/geometry/geometry.py, supervisely/project/project_meta.py
- label.get_mask() to retrieve a binary mask of the label
- geometry.get_mask() to retrieve a binary mask of the geometry
- annotation.get_label_by_id() to get sly.Label by it's ID
- annotation._get_label_tags() to get label's tags in JSON format
- annotation.update_label() to update label on the server from sly.Label
- New ApiFields
- New Event class in subapp.py for representing POST requests to the app
- app.event() decorator to handle POST requests to the app
- is_on() function for Switch widget
- get_obj_class_by_id() for sly.ProjectMeta
=> API get and update label by id, app.event() decorator and sly.Events

supervisely/api/module_api.py, supervisely/app/fastapi/subapp.py, supervisely/geometry/bitmap.py
- sly.Bitmap.base64_2_data() will process uncompressed base64 strings
- new ApiFields
- mask and geometry_type attributes for sly.Event.Brush.DrawLeftMouseReleased
=> Brush.DrawLeftMouseReleased handle masks from the Labeling Tool

supervisely/api/api.py, supervisely/api/image_annotation_tool_api.py, supervisely/api/video_annotation_tool_api.py, supervisely/app/fastapi/subapp.py, supervisely/video/video.py
- Api.vid_ann_tool for Video Labeling Tool
- VideoAnnotationToolApi with two actions: enable_job_controls() and disable_job_controls()
- video.get_labeling_tool_url() improvements: Optional framerate, optional link parameter to retrieve HTML link with one function. Docstrings and typing.
=> Video Labeling Tool API, disabling labeling job buttons, app.Event.ManualSelected.VideoChanged

supervisely/api/dataset_api.py, supervisely/api/module_api.py, supervisely/api/project_api.py
`ApiField`:
- archiving field
- `SILENT`
- `PAGE`
- `remove_permanently` - deletes datasets without saving them to the `Trash Bin`
- `get_list_all` - returns all available datasets matching the specified filtering criteria
- `silent` - new attr for def `update_custom_data` determines whether the `updatedAt` timestamp should be updated or not, if False - update `updatedAt`
- archiving attr - new attr for def `get_archivation_list`
=> new archiving features in project API methods + new dataset API methods

supervisely/project/volume_project.py, supervisely/video_annotation/video_figure.py
- provide more details about figure when raising `OutOfImageBoundsException` exception
- log additional info for debugging if `VolumeAnnotation.from_json` function fails
=> Logging details about Figure in OutOfImageBoundsException and Volume in VolumeAnnotation.from_json

supervisely/api/file_api.py, supervisely/io/env.py, supervisely/io/fs.py, supervisely/output/__init__.py
Reads env variables and detects if file or folder was passed, supports files from agent.
Saves the input in the specified directory:
```python
save_path = "/my_app_data"
api.file.download_input(save_path)
```
=> Download user input in application in one line

supervisely/api/dataset_api.py, supervisely/api/project_api.py
- fix number of entites in response for `"all"`
- change default arg `page` to `"all"`
=> Fix method `get_list_all` for Project and Dataset API

supervisely/api/labeling_job_api.py
=> Fix classes_to_label and tags_to_label fields in LabelingJobInfo

supervisely/annotation/obj_class_collection.py, supervisely/api/report_api.py, supervisely/app/fastapi/index.html, supervisely/app/v1/__init__.py, supervisely/app/widgets/grid_plot/grid_plot.py, supervisely/project/project.py, tests/download_nps_with_generators.py
remove upper padding for body `div` in `index.html`
=> FastApi `index.html` update + cyrillic fixes

supervisely/api/pointcloud/pointcloud_episode_api.py, supervisely/api/volume/volume_api.py
PCD Episodes methods that use `_upload_bulk_add` method will work if meta is None
=> PCD Episodes: Fix(add) frames in meta for _upload_bulk_add 

supervisely/app/v1/app_service.py, supervisely/function_wrapper.py, supervisely/io/exception_handlers.py
- `main_wrapper` - if statement for logging for agent
- `AppService` - `repr(e)` in log message
- `exception_handler` - full log message
=> Tiny updates in error logs (if statement in main_wrapper and updates in error logs)

supervisely/api/image_api.py, supervisely/api/pointcloud/pointcloud_api.py, supervisely/api/video/video_api.py, supervisely/api/volume/volume_api.py, supervisely/io/fs.py, tests/test_api_video.py
- add attribute _skip_name_validation to VideoApi
- add path validation to def upload_paths
- add unit tests
- fix ResourceWarning for def get_file_hash
- update docstring for uploads by adding the extension requirement for names
=> Add attribute _skip_name_validation to VideoApi and validate ext by path in api.video.upload_paths

supervisely/api/volume/volume_api.py, supervisely/volume/volume.py, tests/api_tests/test_api_volume.py
- add defs get_free_names, raise_name_intersections_if_exist, upload_dir, upload_dirs, is_valid_format
- update inspect_dicom_series with logging arg and fix overwriting duplicate series
- update inspect_nrrd_series with logging arg
- add type hints for some method
- fix docstrings
- add tests
=> Volumes: add def `upload_dir` , `upload_dirs`, `is_valid_format`, update `inspect_dicom_series` and `inspect_nrrd_series`

.github/workflows/checking_pull_request_with_pylint.yml, supervisely/api/api.py, supervisely/geometry/bitmap.py, supervisely/geometry/mask_3d.py, supervisely/io/fs.py
- Refactor `archive_directory` funct. to split large parts into particles at creation to avoid an out-of-memory error
- Refactor `unpack_archive` func. to unpack split archives.
- Fix typehint for `external_logger` in `Api.__init__` and update server address in `set_key()` method
- fix string formatting for def `Mask3D.from_json`
- exclude pylint errors
- update pull_request event types to `close` and add condition for merged pull requests in github workflow
=> Fix def `archive_directory` OOM error for parts, refactor def `unpack_archive ` to unpack split archives.

.github/workflows/manual_sdk_docker_only.yml, .github/workflows/manual_sdk_nvidia_docker.yml, .github/workflows/manual_sdk_pip_docker.yml, .github/workflows/sdk_pip_docker.yml
Update checkout and setup-python steps version
=> Update release actions

setup.py, supervisely/geometry/polygon.py, supervisely/geometry/validation.py
- add validation of internal polygon properly containing external polygon with shapely .contains_properly
- update minimal shapely requirement to 2.0.0
- add polygon area calculation considering internal points
=> count polygon's area considering internal polygons

.github/workflows/close_inactive_issues.yml
This will run the task at 2:30 AM every Sunday.
=> Changed cron for inactive issues to once a week

supervisely/api/team_api.py
```python
from supervisely.api.team_api import ActivityAction
stats = api.team.get_activity(
team_id,
labeler_id=340,
review_status="rejected",
filter_actions=[ActivityAction.IMAGE_REVIEW_STATUS_UPDATED],
)
```
=> Statistics for the labeler in team

supervisely/convert/base_converter.py, supervisely/convert/image/coco/coco_converter.py, supervisely/convert/image/image_converter.py, supervisely/convert/image/image_helper.py, supervisely/convert/image/sly/sly_image_converter.py, supervisely/convert/pointcloud/pointcloud_converter.py, supervisely/convert/pointcloud_episodes/pointcloud_episodes_converter.py, supervisely/convert/video/video_converter.py, supervisely/convert/volume/volume_converter.py
- Fix `avif` and `heic` images convert
- Suppress COCO annotation reader
- Fix case sensitive errors
- Add additional dataset validation
=> Image import fixes

supervisely/app/fastapi/templating.py, supervisely/convert/base_converter.py, supervisely/convert/image/coco/coco_converter.py, supervisely/convert/image/coco/coco_helper.py, supervisely/convert/image/image_converter.py, supervisely/convert/image/image_helper.py, supervisely/convert/image/medical2d/medical2d_converter.py, supervisely/convert/image/pascal_voc/pascal_voc_converter.py, supervisely/convert/image/pascal_voc/pascal_voc_helper.py, supervisely/convert/image/sly/sly_image_converter.py, supervisely/convert/pointcloud/pointcloud_converter.py, supervisely/convert/pointcloud_episodes/pointcloud_episodes_converter.py, supervisely/convert/video/video_converter.py, supervisely/convert/volume/volume_converter.py, supervisely/project/project.py
- support for Pascal VOC detection format
- upgrade js bundle to 2.1.80
- fix img2ann mismatching in sly format
- fix AttributeError in COCO format converter and safely suppress prints in COCO class
- allow to detect medical_2d converter for default labeling_interface
- update logging
=> Image Import fixes. Upgrade JS bundle to 2.1.80

docker_images/import_export/Dockerfile, supervisely/convert/__init__.py, supervisely/convert/base_converter.py, supervisely/convert/image/cityscapes/cityscapes_converter.py, supervisely/convert/image/cityscapes/cityscapes_helper.py, supervisely/convert/image/image_helper.py, supervisely/convert/image/masks/images_with_masks_converter.py, supervisely/convert/pointcloud/bag/bag_converter.py, supervisely/convert/pointcloud/bag/bag_helper.py, supervisely/convert/pointcloud_episodes/bag/bag_converter.py, supervisely/convert/pointcloud_episodes/sly/sly_pointcloud_episodes_converter.py, supervisely/pointcloud_annotation/pointcloud_figure.py, supervisely/project/readme_template.md, supervisely/volume_annotation/volume_figure.py
Import updates:
- add new converter from ROS bag files to .pcd (works for clouds and episodes projects)
- add `imagecodecs` library in `import-export` docker image (additional codecs for tiff files)
- improve converter from cityscapes format (generate meta without key file)
- fix PNG mask converter
other changes:
- bugfix: track_id param in `PointcloudFigure` / `VolumeFigure` classes init
- remove unnecessary type hints from readme_template.md
=> New import updates: rosbag, cityscape, PNG mask converters. Fix track_id in PointcloudFigure and VolumeFigure

supervisely/app/widgets/custom_models_selector/custom_models_selector.py, supervisely/app/widgets/pretrained_models_selector/pretrained_models_selector.py, supervisely/app/widgets/pretrained_models_selector/template.html, supervisely/nn/checkpoints/checkpoint.py, supervisely/nn/checkpoints/detectron2.py, supervisely/nn/checkpoints/hrda.py, supervisely/nn/checkpoints/mmclassification.py, supervisely/nn/checkpoints/mmdetection.py, supervisely/nn/checkpoints/mmdetection3.py, supervisely/nn/checkpoints/mmsegmentation.py, supervisely/nn/checkpoints/ritm.py, supervisely/nn/checkpoints/unet.py, supervisely/nn/checkpoints/yolov5.py, supervisely/nn/checkpoints/yolov5_v2.py, supervisely/nn/checkpoints/yolov8.py
**CustomModelsSelector**
- Update link to task file (offline session)
- Sort and filter task types
- Fix selector by row
- Add support for checkpoints with config file
**PretrainedModelsSelector** 
- Add sorting flag. If True models will be sorted by name, else by index in table
- Rework filtering and sorting. 1st filter by task type, then by architecture type
- Add methods `get_available_task_types()`, `get_available_arch_types()`
- Update `get_selected_row()` method
- Add support for checkpoints with config file
=> Update CustomModelsSelector and PretrainedModelsSelector widgets, update session links in checkpoint parsing functions

supervisely/convert/image/image_converter.py
if path is None, then image has failed validation
=> New Import: skip images with invalid mime types

supervisely/io/fs.py
=> Update chunk size to fit split size in archive_directory function

supervisely/nn/inference/cache.py, supervisely/nn/inference/inference.py, supervisely/nn/inference/instance_segmentation/instance_segmentation.py, supervisely/nn/inference/interactive_segmentation/interactive_segmentation.py, supervisely/nn/inference/pose_estimation/pose_estimation.py, supervisely/nn/inference/promptable_segmentation/promptable_segmentation.py, supervisely/nn/inference/salient_object_segmentation/salient_object_segmentation.py, supervisely/nn/inference/semantic_segmentation/semantic_segmentation.py, supervisely/nn/inference/tracking/bbox_tracking.py, supervisely/nn/inference/tracking/mask_tracking.py, supervisely/nn/inference/tracking/point_tracking.py
Refactor Inference subclasses to not inherit from InferenceImageCache
Added classes whitelist setting to the inference methods
Optimized results upload for inference_project_id method
=> Inference Refactor

supervisely/nn/inference/cache.py, supervisely/nn/inference/inference.py
simplify expire() function that was causing errors
=> Simplify Inference Cache

supervisely/convert/converter.py, supervisely/convert/image/pascal_voc/pascal_voc_converter.py, supervisely/convert/image/pascal_voc/pascal_voc_helper.py
- Import as links from Cloud Storage: fix the path for the single file
- Fixes and refactoring in the PascalVoc format converter
=> AutoImport fixes: fix the path for the single file from Cloud Storage. Fix and refactor PascalVOC converter

setup.py
Bump cachetools min version to 4.2.3
=> Bump cachetools min version

supervisely/io/docker_utils.py
Fix progress total to be equal to current in case it is not present
=> Docker utils pull progress fix

supervisely/api/app_api.py
By default is disabled for development mode
=> Enable/disable workflow functionality in AppApi

supervisely/nn/inference/inference.py
- added TASK_ID to os.environ when debug_with_sly_net
- moved gui creation to __init__ to enable local debug
=> Inference improvements for debugging

supervisely/nn/benchmark/visualization/vis_templates.py
Margin fixes for Model benchmark report
=> Model benchmark Report Visualization updates

setup.py, supervisely/api/dataset_api.py, supervisely/api/video/video_annotation_api.py, supervisely/api/video/video_api.py, supervisely/app/widgets/table/template.html
Added Dataset copy and copy_batch for video projects
Fixed bug with table widget
=> Dataset copy and copy_batch for video projects

supervisely/api/api.py
1. Optional Api token
2. https redirect rework
=> Minor Api Updates

supervisely/api/entity_annotation/tag_api.py, supervisely/api/image_api.py, supervisely/api/pointcloud/pointcloud_api.py, supervisely/api/video/video_api.py, supervisely/api/volume/volume_api.py, supervisely/app/fastapi/subapp.py, supervisely/app/v1/__init__.py, supervisely/imaging/image.py, supervisely/pointcloud/pointcloud.py, supervisely/pointcloud_episodes/pointcloud_episodes.py, supervisely/project/project.py, tests/test_async_image_api.py
Add def `get_size_from_bytes` to imaging
=> Add fields arg to image and video items listings. Fix file meta for async download.

supervisely/api/image_api.py
- added new `group_images_for_multiview` method
- added `force_metadata_for_links` arg to `upload_multiview_images`
=> New ImageApi method – group_images_for_multiview

supervisely/geometry/rectangle.py
```
top    left    bottom    right
from       960    1280     801     1116
to         801    1116     960     1280
```
=> Sorting rectangle coordinates before deserialization

supervisely/nn/benchmark/base_benchmark.py, supervisely/nn/benchmark/base_evaluator.py, supervisely/nn/benchmark/instance_segmentation/evaluator.py, supervisely/nn/benchmark/object_detection/evaluator.py, supervisely/nn/benchmark/semantic_segmentation/evaluator.py, supervisely/nn/benchmark/utils/detection/utlis.py
=> Add key_metrics property. Refactor EvalResult to allow to create EvalResult from evaluator class

supervisely/api/api.py, supervisely/project/pointcloud_episode_project.py, supervisely/project/pointcloud_project.py, supervisely/project/project.py, supervisely/project/volume_project.py
Set new semaphore size for Api on app.supervisely
=> Fix Dataset Content Dirs + Add `NotImplementedError` for `download_async` in Volumes, PCD, PCDE

.vscode/settings.json, docker_images/import_export/Dockerfile, supervisely/convert/__init__.py, supervisely/convert/base_converter.py, supervisely/convert/pointcloud/nuscenes_conv/nuscenes_converter.py, supervisely/convert/pointcloud/pointcloud_converter.py, supervisely/convert/pointcloud/sly/sly_pointcloud_converter.py, supervisely/convert/pointcloud/sly/sly_pointcloud_helper.py, supervisely/convert/pointcloud_episodes/lyft/lyft_converter.py, supervisely/convert/pointcloud_episodes/nuscenes/nuscenes_converter.py, supervisely/convert/pointcloud_episodes/nuscenes/nuscenes_helper.py, supervisely/convert/pointcloud_episodes/nuscenes_conv/nuscenes_converter.py, supervisely/convert/pointcloud_episodes/nuscenes_conv/nuscenes_helper.py, supervisely/convert/pointcloud_episodes/pointcloud_episodes_converter.py, supervisely/convert/pointcloud_episodes/sly/sly_pointcloud_episodes_converter.py
- Improve format detection for Supervisely pointcloud & pointcloud episodes converters 
- Add NuScenes pointcloud & pointcloud episodes converter
=> [Auto-Import] Add NuScenes converter for Pointcloud and Pointcloud Episodes

setup.py, supervisely/project/data_version.py, supervisely/project/project.py
Add `name` field to `VersionInfo` class
=> Enhance CustomUnpickler to handle varying Info class definitions

supervisely/_utils.py, supervisely/api/api.py, supervisely/geometry/mask_3d.py, supervisely/io/fs.py, supervisely/io/json.py, supervisely/project/project.py, supervisely/project/video_project.py
[Refactor docstrings](https://github.com/supervisely/supervisely/commit/1a356dcf25e9540de7bb6e35b2b51297b9d1051e)
=> Enhance HTTPS redirect

supervisely/nn/inference/inference.py
Enhance logging for AutoRestartInfo creation and updates
=> Fix updating of AutoRestartInfo when model is updated

supervisely/convert/image/medical2d/medical2d_helper.py
- Convert DICOM to monochrome2 Photometric Interpretation
- Decompress files
=> [Auto-Import] Handle DICOM files with non-monochromatic pixel data for 2D Medical Images converter

supervisely/api/nn/deploy_api.py
- Added dynamic model file path resolution to ensure files exist in the specified artifacts directory.
- Updated module retrieval logic to use framework name instead of task ID for serving applications.
- Enhanced logging for better debugging of model file additions.
=> Refactor DeployApi to improve model file handling and framework detection

supervisely/convert/image/pascal_voc/pascal_voc_converter.py, supervisely/convert/image/pascal_voc/pascal_voc_helper.py
https://github.com/supervisely/issues/issues/5609
=> [Auto-Import] Add object tags to Pascal format

supervisely/nn/training/gui/gui.py, supervisely/nn/training/train_app.py
- Added `save_image_info` parameter to TrainApp for improved image information handling during training.
- Updated TrainGUI to ensure experiment name is validated against empty strings before setting, enhancing robustness in app state management.
=> Fix training process with disabled caching

supervisely/api/image_api.py
https://github.com/supervisely/issues/issues/5687
=> Add `get_subsequent_image_ids` method to ImageApi
